name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build application
        run: go build -v -o ./mws ./main.go

      - name: Run tests and generate coverage report
        run: go test -v -coverprofile=coverage.out ./...

      - name: Update coverage badge
        run: |
          chmod +x ./scripts/update-badge.sh
          ./scripts/update-badge.sh